version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=teekart
      - DB_USER=ritvik
      - DB_PASSWORD=pass123

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: teekart
      POSTGRES_USER: ritvik
      POSTGRES_PASSWORD: pass123
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:

